### ISSUE TITLE
The distribution should not be included in the repo

### ISSUE THREAD

**Issue by codazzo** [BrandwatchLtd/selleckt#73]
I think it's a bit of an anti-pattern as the distribution needs to be occasionally updated in a commit that's interleaved with actual development,  adding noise to the commit history.
I can think of two options:

1) creating a `dist` branch that can be used when importing the package in e.g. `bower.json`
2) Only publishing the artifacts on bower and npm

Either way the work should be done automatically with each change to master with a build task.

**Comment by grahamscott** [comment]
> Only publishing the artifacts on bower and npm

This sounds like the way to go.

**Comment by spmason** [comment]
Can we do that for bower? IIRC it just uses whatever is in the git checkout and doesn't have the concept of a "postinstall" hook or whatever

FWIW the fix for merge conflicts in the `dist/` files is just to regenerate the files...

**Comment by codazzo** [comment]
> Can we do that for bower? IIRC it just uses whatever is in the git checkout and doesn't have the concept of a "postinstall" hook or whatever

The solution then would be to have a different repo like e.g. [ember](https://github.com/components/ember), [mapbox](https://github.com/mapbox/mapbox.js-bower) etc
This would also be automated.

> FWIW the fix for merge conflicts in the dist/ files is just to regenerate the files...

True, but then you have to amend your own 'dist' commit with the new distribution - I find that too error prone.

**Comment by spmason** [comment]
OK makes sense

**Comment by codazzo** [comment]
Inspiration from Ember.js: https://github.com/emberjs/ember.js/blob/master/.travis.yml#L21-L22
